/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BoardRouteImport } from './routes/board'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DonorsRouteImport } from './routes/donors'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as PriestsRouteImport } from './routes/priests'
import { Route as ReceiptRouteImport } from './routes/receipt'
import { Route as TimingsRouteImport } from './routes/timings'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as HallsIndexRouteImport } from './routes/halls.index'
import { Route as PaySlugRouteImport } from './routes/pay.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminCommunityRouteImport } from './routes/_authenticated/admin.community'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin.events'
import { Route as AuthenticatedAdminHallsRouteImport } from './routes/_authenticated/admin.halls'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminPeopleRouteImport } from './routes/_authenticated/admin.people'
import { Route as AuthenticatedAdminPoojasRouteImport } from './routes/_authenticated/admin.poojas'
import { Route as AuthenticatedAdminTempleRouteImport } from './routes/_authenticated/admin.temple'
import { Route as AuthenticatedAdminTimingsRouteImport } from './routes/_authenticated/admin.timings'
import { Route as AuthenticatedBookSlugRouteImport } from './routes/_authenticated/book.$slug'
import { Route as AuthenticatedHallSlugRouteImport } from './routes/_authenticated/hall.$slug'
import { Route as ApiPublicWebhooksSquareRouteImport } from './routes/api/public/webhooks/square'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorsRoute = DonorsRouteImport.update({
  id: '/donors',
  path: '/donors',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const PriestsRoute = PriestsRouteImport.update({
  id: '/priests',
  path: '/priests',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptRoute = ReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const TimingsRoute = TimingsRouteImport.update({
  id: '/timings',
  path: '/timings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HallsIndexRoute = HallsIndexRouteImport.update({
  id: '/halls/',
  path: '/halls/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaySlugRoute = PaySlugRouteImport.update({
  id: '/pay/$slug',
  path: '/pay/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCommunityRoute =
  AuthenticatedAdminCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHallsRoute = AuthenticatedAdminHallsRouteImport.update({
  id: '/halls',
  path: '/halls',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPeopleRoute =
  AuthenticatedAdminPeopleRouteImport.update({
    id: '/people',
    path: '/people',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPoojasRoute =
  AuthenticatedAdminPoojasRouteImport.update({
    id: '/poojas',
    path: '/poojas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTempleRoute =
  AuthenticatedAdminTempleRouteImport.update({
    id: '/temple',
    path: '/temple',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTimingsRoute =
  AuthenticatedAdminTimingsRouteImport.update({
    id: '/timings',
    path: '/timings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedBookSlugRoute = AuthenticatedBookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHallSlugRoute = AuthenticatedHallSlugRouteImport.update({
  id: '/hall/$slug',
  path: '/hall/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWebhooksSquareRoute = ApiPublicWebhooksSquareRouteImport.update({
  id: '/api/public/webhooks/square',
  path: '/api/public/webhooks/square',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/board': typeof BoardRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/donors': typeof DonorsRoute
  '/library': typeof LibraryRoute
  '/priests': typeof PriestsRoute
  '/receipt': typeof ReceiptRoute
  '/timings': typeof TimingsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/events/$slug': typeof EventsSlugRoute
  '/pay/$slug': typeof PaySlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/events/': typeof EventsIndexRoute
  '/halls/': typeof HallsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/community': typeof AuthenticatedAdminCommunityRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/halls': typeof AuthenticatedAdminHallsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/admin/poojas': typeof AuthenticatedAdminPoojasRoute
  '/admin/temple': typeof AuthenticatedAdminTempleRoute
  '/admin/timings': typeof AuthenticatedAdminTimingsRoute
  '/book/$slug': typeof AuthenticatedBookSlugRoute
  '/hall/$slug': typeof AuthenticatedHallSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/square': typeof ApiPublicWebhooksSquareRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/board': typeof BoardRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/donors': typeof DonorsRoute
  '/library': typeof LibraryRoute
  '/priests': typeof PriestsRoute
  '/receipt': typeof ReceiptRoute
  '/timings': typeof TimingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/events/$slug': typeof EventsSlugRoute
  '/pay/$slug': typeof PaySlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/events': typeof EventsIndexRoute
  '/halls': typeof HallsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/community': typeof AuthenticatedAdminCommunityRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/halls': typeof AuthenticatedAdminHallsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/admin/poojas': typeof AuthenticatedAdminPoojasRoute
  '/admin/temple': typeof AuthenticatedAdminTempleRoute
  '/admin/timings': typeof AuthenticatedAdminTimingsRoute
  '/book/$slug': typeof AuthenticatedBookSlugRoute
  '/hall/$slug': typeof AuthenticatedHallSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/square': typeof ApiPublicWebhooksSquareRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/board': typeof BoardRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/donors': typeof DonorsRoute
  '/library': typeof LibraryRoute
  '/priests': typeof PriestsRoute
  '/receipt': typeof ReceiptRoute
  '/timings': typeof TimingsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/events/$slug': typeof EventsSlugRoute
  '/pay/$slug': typeof PaySlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/events/': typeof EventsIndexRoute
  '/halls/': typeof HallsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/community': typeof AuthenticatedAdminCommunityRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/halls': typeof AuthenticatedAdminHallsRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/_authenticated/admin/poojas': typeof AuthenticatedAdminPoojasRoute
  '/_authenticated/admin/temple': typeof AuthenticatedAdminTempleRoute
  '/_authenticated/admin/timings': typeof AuthenticatedAdminTimingsRoute
  '/_authenticated/book/$slug': typeof AuthenticatedBookSlugRoute
  '/_authenticated/hall/$slug': typeof AuthenticatedHallSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/square': typeof ApiPublicWebhooksSquareRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/board'
    | '/calendar'
    | '/contact'
    | '/donate'
    | '/donors'
    | '/library'
    | '/priests'
    | '/receipt'
    | '/timings'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/auth/callback'
    | '/events/$slug'
    | '/pay/$slug'
    | '/services/$slug'
    | '/events/'
    | '/halls/'
    | '/services/'
    | '/admin/audit'
    | '/admin/community'
    | '/admin/events'
    | '/admin/halls'
    | '/admin/payments'
    | '/admin/people'
    | '/admin/poojas'
    | '/admin/temple'
    | '/admin/timings'
    | '/book/$slug'
    | '/hall/$slug'
    | '/admin/'
    | '/api/public/webhooks/square'
    | '/api/public/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/board'
    | '/calendar'
    | '/contact'
    | '/donate'
    | '/donors'
    | '/library'
    | '/priests'
    | '/receipt'
    | '/timings'
    | '/dashboard'
    | '/profile'
    | '/auth/callback'
    | '/events/$slug'
    | '/pay/$slug'
    | '/services/$slug'
    | '/events'
    | '/halls'
    | '/services'
    | '/admin/audit'
    | '/admin/community'
    | '/admin/events'
    | '/admin/halls'
    | '/admin/payments'
    | '/admin/people'
    | '/admin/poojas'
    | '/admin/temple'
    | '/admin/timings'
    | '/book/$slug'
    | '/hall/$slug'
    | '/admin'
    | '/api/public/webhooks/square'
    | '/api/public/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/board'
    | '/calendar'
    | '/contact'
    | '/donate'
    | '/donors'
    | '/library'
    | '/priests'
    | '/receipt'
    | '/timings'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/auth/callback'
    | '/events/$slug'
    | '/pay/$slug'
    | '/services/$slug'
    | '/events/'
    | '/halls/'
    | '/services/'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/community'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/halls'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/people'
    | '/_authenticated/admin/poojas'
    | '/_authenticated/admin/temple'
    | '/_authenticated/admin/timings'
    | '/_authenticated/book/$slug'
    | '/_authenticated/hall/$slug'
    | '/_authenticated/admin/'
    | '/api/public/webhooks/square'
    | '/api/public/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  BoardRoute: typeof BoardRoute
  CalendarRoute: typeof CalendarRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  DonorsRoute: typeof DonorsRoute
  LibraryRoute: typeof LibraryRoute
  PriestsRoute: typeof PriestsRoute
  ReceiptRoute: typeof ReceiptRoute
  TimingsRoute: typeof TimingsRoute
  EventsSlugRoute: typeof EventsSlugRoute
  PaySlugRoute: typeof PaySlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  EventsIndexRoute: typeof EventsIndexRoute
  HallsIndexRoute: typeof HallsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ApiPublicWebhooksSquareRoute: typeof ApiPublicWebhooksSquareRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donors': {
      id: '/donors'
      path: '/donors'
      fullPath: '/donors'
      preLoaderRoute: typeof DonorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priests': {
      id: '/priests'
      path: '/priests'
      fullPath: '/priests'
      preLoaderRoute: typeof PriestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt': {
      id: '/receipt'
      path: '/receipt'
      fullPath: '/receipt'
      preLoaderRoute: typeof ReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timings': {
      id: '/timings'
      path: '/timings'
      fullPath: '/timings'
      preLoaderRoute: typeof TimingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/halls/': {
      id: '/halls/'
      path: '/halls'
      fullPath: '/halls/'
      preLoaderRoute: typeof HallsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$slug': {
      id: '/pay/$slug'
      path: '/pay/$slug'
      fullPath: '/pay/$slug'
      preLoaderRoute: typeof PaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/community': {
      id: '/_authenticated/admin/community'
      path: '/community'
      fullPath: '/admin/community'
      preLoaderRoute: typeof AuthenticatedAdminCommunityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/halls': {
      id: '/_authenticated/admin/halls'
      path: '/halls'
      fullPath: '/admin/halls'
      preLoaderRoute: typeof AuthenticatedAdminHallsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/people': {
      id: '/_authenticated/admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AuthenticatedAdminPeopleRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/poojas': {
      id: '/_authenticated/admin/poojas'
      path: '/poojas'
      fullPath: '/admin/poojas'
      preLoaderRoute: typeof AuthenticatedAdminPoojasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/temple': {
      id: '/_authenticated/admin/temple'
      path: '/temple'
      fullPath: '/admin/temple'
      preLoaderRoute: typeof AuthenticatedAdminTempleRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/timings': {
      id: '/_authenticated/admin/timings'
      path: '/timings'
      fullPath: '/admin/timings'
      preLoaderRoute: typeof AuthenticatedAdminTimingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/book/$slug': {
      id: '/_authenticated/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof AuthenticatedBookSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hall/$slug': {
      id: '/_authenticated/hall/$slug'
      path: '/hall/$slug'
      fullPath: '/hall/$slug'
      preLoaderRoute: typeof AuthenticatedHallSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/square': {
      id: '/api/public/webhooks/square'
      path: '/api/public/webhooks/square'
      fullPath: '/api/public/webhooks/square'
      preLoaderRoute: typeof ApiPublicWebhooksSquareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminCommunityRoute: typeof AuthenticatedAdminCommunityRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminHallsRoute: typeof AuthenticatedAdminHallsRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPeopleRoute: typeof AuthenticatedAdminPeopleRoute
  AuthenticatedAdminPoojasRoute: typeof AuthenticatedAdminPoojasRoute
  AuthenticatedAdminTempleRoute: typeof AuthenticatedAdminTempleRoute
  AuthenticatedAdminTimingsRoute: typeof AuthenticatedAdminTimingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminCommunityRoute: AuthenticatedAdminCommunityRoute,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
  AuthenticatedAdminHallsRoute: AuthenticatedAdminHallsRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminPeopleRoute: AuthenticatedAdminPeopleRoute,
  AuthenticatedAdminPoojasRoute: AuthenticatedAdminPoojasRoute,
  AuthenticatedAdminTempleRoute: AuthenticatedAdminTempleRoute,
  AuthenticatedAdminTimingsRoute: AuthenticatedAdminTimingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedBookSlugRoute: typeof AuthenticatedBookSlugRoute
  AuthenticatedHallSlugRoute: typeof AuthenticatedHallSlugRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedBookSlugRoute: AuthenticatedBookSlugRoute,
  AuthenticatedHallSlugRoute: AuthenticatedHallSlugRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  BoardRoute: BoardRoute,
  CalendarRoute: CalendarRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  DonorsRoute: DonorsRoute,
  LibraryRoute: LibraryRoute,
  PriestsRoute: PriestsRoute,
  ReceiptRoute: ReceiptRoute,
  TimingsRoute: TimingsRoute,
  EventsSlugRoute: EventsSlugRoute,
  PaySlugRoute: PaySlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  EventsIndexRoute: EventsIndexRoute,
  HallsIndexRoute: HallsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ApiPublicWebhooksSquareRoute: ApiPublicWebhooksSquareRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
